site_name: My Docs
site_url: https://binayshaw7777.github.io/kotstep

nav:
  - Home: index.md
  - Guide:
      - Installation: guide/installation.md
      - Usage: guide/usage.md
  - About: about.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: deepPurple
      accent: orange 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: deepPurple
      accent: amber


copyright: |
  &copy; 2023 <a href="https://github.com/binayshaw7777"  target="_blank" rel="noopener">Binay Shaw</a>